#ifndef READERFRAME_GLOBAL_H
#define READERFRAME_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(READERFRAME_LIBRARY)
#  define READERFRAMESHARED_EXPORT Q_DECL_EXPORT
#else
#  define READERFRAMESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // READERFRAME_GLOBAL_H
